services:
  slurmjupyter:
        image: jupyter
        hostname: slurmjupyter
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 8888:8888
  slurmmaster:
        image: masterslurm
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        image: nodeslurm
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode2:
        image: nodeslurm
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode3:
        image: nodeslurm
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
volumes:
        shared-vol:

